### ISSUE TITLE
channel id is empty

### ISSUE THREAD

**Issue by SerBad** [line/line-sdk-android#136]
I found crash on online version.I check my code, I  set currect chennel Id when launch line.
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{/com.linecorp.linesdk.openchat.ui.CreateOpenChatActivity}: java.lang.IllegalArgumentException: channel id is empty
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by plateaukao** [comment]
Hi, @SerBad 
Please help to provide a sample app that could reproduce the issue you mentioned, so that we could look into this issue much faster. Thank you.
