### ISSUE TITLE
android.security.KeyStoreException occuring while trying to login with Line - sdk-version:5.10.1

### ISSUE THREAD

**Issue by shakil-bin-karim** [line/line-sdk-android#170]
## What did you do?

> Try to authenticate users with Line.

## What did you expect?

> User's getting authenticated with Line.

## What happened actually?

Some users were experiencing crashes while trying to login with Line as we updated SDK to v5.10.1. It is occurring due to KeyStoreException. Currently this is only occurring in one particular phone model: Oppo Reno5 A. 

Stack trace 
```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$4.done(AsyncTask.java:415)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
       at java.util.concurrent.FutureTask.run(FutureTask.java:269)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

Caused by com.linecorp.linesdk.internal.security.encryption.EncryptionException: Failed to encrypt
       at com.linecorp.linesdk.internal.security.encryption.StringAesCipher.encrypt(StringAesCipher.kt:63)
       at com.linecorp.linesdk.internal.AccessTokenCache.encryptString(AccessTokenCache.java:99)
       at com.linecorp.linesdk.internal.AccessTokenCache.saveAccessToken(AccessTokenCache.java:60)
       at com.linecorp.linesdk.auth.internal.LineAuthenticationController$AccessTokenRequestTask.doInBackground(LineAuthenticationController.java:242)
       at com.linecorp.linesdk.auth.internal.LineAuthenticationController$AccessTokenRequestTask.doInBackground(LineAuthenticationController.java:203)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

Caused by java.security.ProviderException: Keystore operation failed
       at android.security.keystore2.AndroidKeyStoreHmacSpi.engineDoFinal(AndroidKeyStoreHmacSpi.java:241)
       at javax.crypto.Mac.doFinal(Mac.java:667)
       at javax.crypto.Mac.doFinal(Mac.java:742)
       at com.linecorp.linesdk.internal.security.encryption.StringAesCipher.calculateHmacValue(StringAesCipher.kt:154)
       at com.linecorp.linesdk.internal.security.encryption.StringAesCipher.encrypt(StringAesCipher.kt:60)
       at com.linecorp.linesdk.internal.AccessTokenCache.encryptString(AccessTokenCache.java:99)
       at com.linecorp.linesdk.internal.AccessTokenCache.saveAccessToken(AccessTokenCache.java:60)
       at com.linecorp.linesdk.auth.internal.LineAuthenticationController$AccessTokenRequestTask.doInBackground(LineAuthenticationController.java:242)
       at com.linecorp.linesdk.auth.internal.LineAuthenticationController$AccessTokenRequestTask.doInBackground(LineAuthenticationController.java:203)
       at android.os.AsyncTask$3.call(AsyncTask.java:394)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

Caused by android.security.KeyStoreException: Invalid operation handle
       at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:356)
       at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
       at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:127)
```

## Your environment?
> LINE SDK version 5.10.1
    Andorid version -12
    Phone Model - Oppo Reno5 A

**Comment by W-Rd41** [comment]
same here with 

LINE SDK version 5.10.1
Android Version 14
OPPO Reno8 5G

**Comment by seankim-android** [comment]
Hi team, any update on this? We have some devices running into the similar issue

List of device:

* Mediatek MT8188G Detachable
* Pixel 5
* Oppo Reno5 A
* CPH2309
* Moto G85 5G

```

Fatal Exception: java.security.InvalidKeyException: Keystore operation failed
       at android.security.keystore2.KeyStoreCryptoOperationUtils.getInvalidKeyException(KeyStoreCryptoOperationUtils.java:130)
       at android.security.keystore2.AndroidKeyStoreHmacSpi.ensureKeystoreOperationInitialized(AndroidKeyStoreHmacSpi.java:185)
       at android.security.keystore2.AndroidKeyStoreHmacSpi.engineInit(AndroidKeyStoreHmacSpi.java:107)
       at javax.crypto.Mac.chooseProvider(Mac.java:443)
       at javax.crypto.Mac.init(Mac.java:513)
       at com.linecorp.linesdk.internal.security.encryption.StringAesCipher.initialize(StringAesCipher.java:40)
       at com.linecorp.linesdk.internal.EncryptorHolder$EncryptorInitializationTask.run(EncryptorHolder.java:48)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
        

```

**Comment by hello-coder-xu** [comment]
I found that 5.10.0 changed the StringCipher encryption implementation. I recently upgraded from 5.8.1 -> 5.11.0 and my ZenFone Max M2 and Realme GT NEO 3T started to crash.

`Caused by android.security.KeyStoreException: -49
       at android.security.KeyStore.getKeyStoreException(KeyStore.java:850)
       at android.security.keystore.AndroidKeyStoreKeyGeneratorSpi.engineGenerateKey(AndroidKeyStoreKeyGeneratorSpi.java:328)
       at javax.crypto.KeyGenerator.generateKey(KeyGenerator.java:612)
       at com.linecorp.linesdk.internal.security.encryption.StringAesCipher.createAesKey(StringAesCipher.kt:132)
       at com.linecorp.linesdk.internal.security.encryption.StringAesCipher.getAesSecretKey(StringAesCipher.kt:98)
       at com.linecorp.linesdk.internal.security.encryption.StringAesCipher.initialize(StringAesCipher.kt:36)
       at com.linecorp.linesdk.internal.EncryptorHolder$EncryptorInitializationTask.run(EncryptorHolder.java:48)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)`


Hi team, any update on this? We have some devices running into the similar issue
