### ISSUE TITLE
LineLoginButton not work with IDToken

### ISSUE THREAD

**Issue by perthcpe23** [line/line-sdk-android#2]
## What did you do?
I followed your example, but I also need user's email so I added two more scopes, Open ID Connect, and Email in MenuFragment.java:78.

I did config Channel's permission to allow access to user's email.
```java
// before
lineLoginButton.setAuthenticationParams(new LineAuthenticationParams.Builder()
    .scopes(Arrays.asList(Scope.PROFILE))
    .build()
);

// after
lineLoginButton.setAuthenticationParams(new LineAuthenticationParams.Builder()
    .scopes(Arrays.asList(Scope.PROFILE,Scope.OPENID_CONNECT,Scope.OC_EMAIL))
    .build()
);
```

## What did you expect?
I expected an Email from login result
```java
@Override
public void onLoginSuccess(@NonNull LineLoginResult result) {
    Toast.makeText(getContext(), result.getLineIdToken().getEmail(),Toast.LENGTH_SHORT).show();
}
```

## What happened actually?
I got error saying
```
2018-11-29 11:09:08.416 8036-8231/com.linecorp.linesdktest E/IdTokenParser: failed to parse IdToken: [REMOVED]
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri$Builder android.net.Uri.buildUpon()' on a null object reference
        at com.linecorp.linesdk.utils.UriUtils.uriBuilder(UriUtils.java:23)
        at com.linecorp.linesdk.utils.UriUtils.buildUri(UriUtils.java:49)
        at com.linecorp.linesdk.internal.nwclient.LineAuthenticationApiClient.getOpenIdDiscoveryDocument(LineAuthenticationApiClient.java:262)
        at com.linecorp.linesdk.internal.nwclient.LineAuthenticationApiClient.getJWKSet(LineAuthenticationApiClient.java:278)
        at com.linecorp.linesdk.internal.nwclient.OpenIdSigningKeyResolver.resolveSigningKey(OpenIdSigningKeyResolver.java:82)
        at com.linecorp.linesdk.internal.nwclient.OpenIdSigningKeyResolver.resolveSigningKey(OpenIdSigningKeyResolver.java:73)
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:342)
        at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:513)
        at io.jsonwebtoken.impl.DefaultJwtParser.parseClaimsJws(DefaultJwtParser.java:573)
        at com.linecorp.linesdk.internal.nwclient.IdTokenParser.parse(IdTokenParser.java:36)
        at com.linecorp.linesdk.internal.nwclient.LineAuthenticationApiClient$IssueAccessTokenResultParser.parseIdToken(LineAuthenticationApiClient.java:167)
        at com.linecorp.linesdk.internal.nwclient.LineAuthenticationApiClient$IssueAccessTokenResultParser.parseJsonToObject(LineAuthenticationApiClient.java:154)
        at com.linecorp.linesdk.internal.nwclient.LineAuthenticationApiClient$IssueAccessTokenResultParser.parseJsonToObject(LineAuthenticationApiClient.java:133)
        at com.linecorp.linesdk.internal.nwclient.JsonToObjectBaseResponseParser.getResponseData(JsonToObjectBaseResponseParser.java:39)
        at com.linecorp.linesdk.internal.nwclient.core.ChannelServiceHttpClient.getChannelServiceResponse(ChannelServiceHttpClient.java:335)
        at com.linecorp.linesdk.internal.nwclient.core.ChannelServiceHttpClient.post(ChannelServiceHttpClient.java:101)
        at com.linecorp.linesdk.internal.nwclient.LineAuthenticationApiClient.issueAccessToken(LineAuthenticationApiClient.java:126)
        at com.linecorp.linesdk.auth.internal.LineAuthenticationController$AccessTokenRequestTask.doInBackground(LineAuthenticationController.java:250)
        at com.linecorp.linesdk.auth.internal.LineAuthenticationController$AccessTokenRequestTask.doInBackground(LineAuthenticationController.java:231)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

## How to fix
Turned out openidDiscoveryDocumentUrl has been null all along.
So I added this line at LineAuthenticationConfig.java:166
```java
openidDiscoveryDocumentUrl = Uri.parse(BuildConfig.OPENID_DISCOVERY_DOCUMENT_URL); // add this line
```

So that it looks like this:
```java
// before
public Builder(@NonNull String channelId) {
    if (TextUtils.isEmpty(channelId)) {
        throw new IllegalArgumentException("channelId is empty.");
    }
    this.channelId = channelId;
    apiBaseUrl = Uri.parse(BuildConfig.API_SERVER_BASE_URI);
    webLoginPageUrl = Uri.parse(BuildConfig.WEB_LOGIN_PAGE_URL);
}

// after
public Builder(@NonNull String channelId) {
    if (TextUtils.isEmpty(channelId)) {
        throw new IllegalArgumentException("channelId is empty.");
    }
    this.channelId = channelId;
    apiBaseUrl = Uri.parse(BuildConfig.API_SERVER_BASE_URI);
    webLoginPageUrl = Uri.parse(BuildConfig.WEB_LOGIN_PAGE_URL);
    openidDiscoveryDocumentUrl = Uri.parse(BuildConfig.OPENID_DISCOVERY_DOCUMENT_URL); // add this line
}
```

Then my issue was solved, but I'm not sure I solved it properly or by accident. Please check.

## Your environment?
Android 8.1.0
Line SDK version 5.0.0
Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

## Sample project
Forked project: https://github.com/perthcpe23/line-sdk-android

**Comment by perthcpe23** [comment]
Thank you. I edited a code as you suggested and sent a PR.

**Comment by LiYing2010** [comment]
hi  @perthcpe23  :
your PR was merged, and will be released with next version soon.
Thanks very much for your help
