### ISSUE TITLE
[Android]Crash parser when use scope Scope.PROFILE, Scope.OPENID_CONNECT,Scope.OC_EMAIL

### ISSUE THREAD

**Issue by cobay333** [line/line-sdk-android#6]
I use line-sdk-5.0.0.aar for my application 
i use custom authentication with code :
 Intent loginIntent = LineLoginApi.getLoginIntent(
                    LoginActivity.this,
                    Constant.CHANEL_ID,
                    new LineAuthenticationParams.Builder()
                            .scopes(Arrays.asList(Scope.PROFILE, Scope.OPENID_CONNECT,Scope.OC_EMAIL))
                            .build());
            startActivityForResult(loginIntent, Constant.REQUEST_CODE_LINE);

I give response : 

java.io.IOException: org.json.JSONException: Attempt to invoke virtual method 'android.net.Uri$Builder android.net.Uri.buildUpon()' on a null object reference
	at com.linecorp.linesdk.internal.nwclient.JsonToObjectBaseResponseParser.getResponseData(JsonToObjectBaseResponseParser.java:41)
	at com.linecorp.linesdk.internal.nwclient.core.ChannelServiceHttpClient.getChannelServiceResponse(ChannelServiceHttpClient.java:335)
	at com.linecorp.linesdk.internal.nwclient.core.ChannelServiceHttpClient.post(ChannelServiceHttpClient.java:101)
	at com.linecorp.linesdk.auth.internal.LineAuthenticationController$AccessTokenRequestTask.doInBackground(LineAuthenticationController.java:5126)
	at com.linecorp.linesdk.auth.internal.LineAuthenticationController$AccessTokenRequestTask.doInBackground(LineAuthenticationController.java:231)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: org.json.JSONException: Attempt to invoke virtual method 'android.net.Uri$Builder android.net.Uri.buildUpon()' on a null object reference
	at com.linecorp.linesdk.internal.nwclient.LineAuthenticationApiClient$IssueAccessTokenResultParser.parseJsonToObject(LineAuthenticationApiClient.java:156)
	at com.linecorp.linesdk.internal.nwclient.LineAuthenticationApiClient$IssueAccessTokenResultParser.parseJsonToObject(LineAuthenticationApiClient.java:133)
	at com.linecorp.linesdk.internal.nwclient.JsonToObjectBaseResponseParser.getResponseData(JsonToObjectBaseResponseParser.java:39)
	... 10 more

PLEASE HELP ME Resolve it
Thanks

**Comment by LiYing2010** [comment]
Hi  @cobay333 :
Thanks very much for reporting this.
Looks like this is same with issue #2 , which was already fixed in PR #3 ,
but we forgot to release a new version inculde this fix.

We will release is soon.

Very sorry for the inconvenience.

**Comment by LiYing2010** [comment]
Hi @plateaukao :

This bug was already fixed in PR #3 , and I upgraded the version number to `5.0.1` in PR #4 .
Could you please build a new release?

**Comment by LiYing2010** [comment]
Hi @cobay333 :
We have released [v5.0.1 ](https://github.com/line/line-sdk-android/releases/tag/v5.0.1) .
Please check if it works
