### ISSUE TITLE
E/AndroidRuntime: FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by DrAugus** [line/line-sdk-android#96]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/linecorp/linesdk/R$layout;
        at com.linecorp.linesdk.auth.internal.LineAuthenticationActivity.onCreate(LineAuthenticationActivity.java:66)
        at android.app.Activity.performCreate(Activity.java:5990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.linecorp.linesdk.R$layout"

**Comment by plateaukao** [comment]
Hi, @DrAugus , could you follow the issue template to provide necessary information? With only error log snippet, it's hard to check why it happened.

**Comment by DrAugus** [comment]
> Hi, @DrAugus , could you follow the issue template to provide necessary information? With only error log snippet, it's hard to check why it happened.

I've found the problem, I made the mistake of calling the function =.=

**Comment by Morteza77777** [comment]
Can you please tell me how can I solve it

**Comment by DrAugus** [comment]
> Hi,@DrAugus,Can you please tell me how can I solve it

https://www.jianshu.com/p/eb7ceb42e263
